# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Main'
on:
  workflow_call:
    inputs:
      mode:
        type: string
      alphas:
        type: string
        default: '["default"]'
      nav:
        type: string
        default: '["default"]'
      clipboard:
        type: string
        default: '["default"]'
      layers:
        type: string
        default: '["default"]'
      mapping:
        type: string
        default: '["default"]'
      kmonad_os:
        type: string
        default: '["default"]'
      rules:
        type: string
        default: '["default"]'
      custom_config:
        type: string
        default: '["default"]'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ${{ fromJSON(inputs.mode) }}
        alphas: ${{ fromJSON(inputs.alphas) }}
        nav: ${{ fromJSON(inputs.nav) }}
        clipboard: ${{ fromJSON(inputs.clipboard) }}
        layers: ${{ fromJSON(inputs.layers) }}
        mapping: ${{ fromJSON(inputs.mapping) }}
        kmonad_os: ${{ fromJSON(inputs.kmonad_os) }}
        rules: ${{ fromJSON(inputs.rules) }}
        custom_config: ${{ fromJSON(inputs.custom_config) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Process inputs
        id: inputs
        run: |
          artifacts_dir="artifacts"
          mkdir "$artifacts_dir"
          src='src'
          build="$src/build"
          rules="$src/custom_rules.mk"
          config="$src/custom_config.h"
          artifact_build_name='miryoku_kmonad'
          for option in "alphas=${{ matrix.alphas }}" "nav=${{ matrix.nav }}" "clipboard=${{ matrix.clipboard }}" "layers=${{ matrix.layers }}" "mapping=${{ matrix.mapping }}" "kmonad_os=${{ matrix.kmonad_os }}"
          do
            if ! expr "$option" : '.*=default$'
            then
                artifact_build_name="$artifact_build_name "`echo "$option" | tr '=' '_'`
                option=`echo "MIRYOKU_$option" | tr 'a-z' 'A-Z'`
                echo "$option" >> "$rules"
            fi
          done
          if [ -n "${{ matrix.rules }}" -a "${{ matrix.rules }}" != 'default' ]
          then
            artifact_build_name="$artifact_build_name rules_"`echo "${{ matrix.rules }}" | md5sum | cut -d ' ' -f 1`
            echo "${{ matrix.rules }}" >> "$rules"
          fi
          if [ -n "${{ matrix.custom_config }}" -a "${{ matrix.custom_config }}" != 'default' ]
          then
            artifact_build_name="$artifact_build_name config_"`echo "${{ matrix.custom_config }}" | md5sum | cut -d ' ' -f 1`
            echo "${{ matrix.custom_config }}" >> "$config"
          fi
          cp "$rules" "$config" "$artifacts_dir"
          artifact_build_name=`echo $artifact_build_name | tr ' ' '-'`
          echo "artifact_dir=$artifacts_dir" >> $GITHUB_OUTPUT
          echo "artifact_build_name=$artifact_build_name" >> $GITHUB_OUTPUT
          echo "src=src" >> $GITHUB_OUTPUT
          echo "build=$build" >> $GITHUB_OUTPUT
          echo "kmonad_file_pattern=kmonad-*-linux" >> $GITHUB_OUTPUT
          echo "kmonad_dir=.github/workflows/bin" >> $GITHUB_OUTPUT
      - name: Remove Build
        if: ${{ matrix.mode == 'test' }}
        run: |
          rm -r "${{ steps.inputs.outputs.build }}"
          mkdir "${{ steps.inputs.outputs.build }}"
          git status -s "${{ steps.inputs.outputs.build }}"
      - name: Build
        run: cd "${{ steps.inputs.outputs.src }}" && make
      - name: Copy config
        if: ${{ matrix.mode == 'build' }}
        run: |
          for file in "${{ steps.inputs.outputs.build }}"/*
          do
            if [ -f "$file" ]
            then
              cp "$file" "${{ steps.inputs.outputs.artifact_dir }}"
            fi
          done
      - name: Diff
        if: ${{ matrix.mode == 'test' }}
        run: |
          git status -s "${{ steps.inputs.outputs.build }}"
          git diff --exit-code "${{ steps.inputs.outputs.build }}"
      - name: Download kmonad release
        if: ${{ matrix.mode == 'test' }}
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "kmonad/kmonad"
          # latest: true
          tag: "0.4.1"
          fileName: "${{ steps.inputs.outputs.kmonad_file_pattern }}"
          out-file-path: "${{ steps.inputs.outputs.kmonad_dir }}"
      - name: Dry run
        if: ${{ matrix.mode == 'test' }}
        run: |
          kmonad=`echo ${{ steps.inputs.outputs.kmonad_dir }}/${{ steps.inputs.outputs.kmonad_file_pattern }}`
          chmod u+x "$kmonad"
          for f in "${{ steps.inputs.outputs.build }}"/*.kbd
          do
            "$kmonad" -d "$f"
          done
      - name: Archive Artifacts
        if: ${{ matrix.mode == 'build' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.inputs.outputs.artifact_build_name }}
          path: ${{ steps.inputs.outputs.artifact_dir }}
